Added pdf resources for html study
1gne0u5/Learning-Resources pull request #40
Opened 2020-10-07 05:23 UTC by noobkid2411

PDF material for introductory course on web developement. 
Kindly check the request and please add hacktober-accepted if the resources seem valuable.Thanks!

2020-10-07 07:02 UTC, blank-27 approved these changes
looks good to me

2020-10-07 08:22 UTC, 3scava1i3r commented
please join the [discord](https://discord.gg/6QAjyBa) server here and add your discord handle in the PR

2020-10-07 09:08 UTC, aksh1407 requested changes
We would prefer links rather than pdfs ripped off of web pages. Kindly update the readme files in respective folders with useful resource links rather than the pdf files. Thank You.

2020-10-07 10:02 UTC, noobkid2411 commented
> We would prefer links rather than pdfs ripped off of web pages. Kindly update the readme files in respective folders with useful resource links rather than the pdf files. Thank You.

Edited and added resources' link to the resources . Kindly check now.

2020-10-07 10:04 UTC, aksh1407 requested changes
Kindly remove files from Designing directory as well.

2020-10-07 10:27 UTC, blank-27 commented
@noobkid2411 please stop spamming here. Join over discord server if you need some help ,we are happy to help

2020-10-07 10:32 UTC, noobkid2411 commented
Yes,sorry for leaving out.Done now,hope it's alright now!

2020-10-07 10:39 UTC, blank-27 requested changes
need changes

2020-10-07 10:59 UTC, archana-17 commented
Please check in the ML resources "Curated list of AI/ML resources" link is not working. @noobkid2411

2020-10-08 03:07 UTC, aksh1407 reviewed
These links are not of much use.

2020-10-08 03:07 UTC, aksh1407 commented on Web Development/Resources/README.md
> +- [Web developement courses on coursera](https://www.coursera.org/courses%3Fquery%3Dweb%2520development&ved=2ahUKEwiLzJXwlKLsAhV8wTgGHfi6AG8QFjAJegQIIBAH&usg=AOvVaw3RaH7LlNPk66swGThS5zNv)
This link does not work. Even if it did, why would someone use this link to search Web Development Courses on Coursera when they can do that already on Coursera itself.

2020-10-08 03:07 UTC, aksh1407 commented on Web Development/Resources/README.md
> +- [Best web developement courses for beginners](https://studywebdevelopment.com/web-development-courses.html)
Same is the case with this.

2020-10-08 03:07 UTC, aksh1407 commented on Web Development/Resources/README.md
> +- [Complete web developement course by edureka](https://m.youtube.com/watch%3Fv%3DQ33KBiDriJY&ved=2ahUKEwiLzJXwlKLsAhV8wTgGHfi6AG8QwqsBMA56BAgSEAM&usg=AOvVaw1-yMWJLtJSaRL4WFL1vAiC)
This is a link for Smartphone browsers.

2020-10-08 03:11 UTC, aksh1407 commented
I am closing this PR since it is cluttered and does not contain content of much use. Create a fresh PR with helpful and usable content for further contribution.

2020-10-08 03:11 UTC, closed without merging